// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: f6qpwMfQ9K36cBNMUgXnEq
// Component: ycBHt6bBw_
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { LottieWrapper } from "@plasmicpkgs/lottie-react"; // plasmic-import: BPNsJ2qis6/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: f6qpwMfQ9K36cBNMUgXnEq/projectcss
import sty from "./PlasmicChat1.module.css"; // plasmic-import: ycBHt6bBw_/css

export type PlasmicChat1__VariantMembers = {};
export type PlasmicChat1__VariantsArgs = {};
type VariantPropType = keyof PlasmicChat1__VariantsArgs;
export const PlasmicChat1__VariantProps = new Array<VariantPropType>();

export type PlasmicChat1__ArgsType = {};
type ArgPropType = keyof PlasmicChat1__ArgsType;
export const PlasmicChat1__ArgProps = new Array<ArgPropType>();

export type PlasmicChat1__OverridesType = {
  root?: p.Flex<typeof LottieWrapper>;
};

export interface DefaultChat1Props {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicChat1__RenderFunc(props: {
  variants: PlasmicChat1__VariantsArgs;
  args: PlasmicChat1__ArgsType;
  overrides: PlasmicChat1__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <LottieWrapper
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      animationData={{
        nm: "Chat",
        mn: "",
        layers: [
          {
            ty: 0,
            nm: "Hovering Dots",
            mn: "",
            sr: 0.5,
            st: 0,
            op: 408,
            ip: 219,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            hasMask: false,
            ao: 0,
            ks: {
              a: { a: 0, k: [400, 400, 0], ix: 1 },
              s: { a: 0, k: [30, 30, 100], ix: 6 },
              sk: { a: 0, k: 0 },
              p: { a: 0, k: [75.078, -24.852, 0], ix: 2 },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: 0, ix: 10 }
            },
            ef: [],
            w: 800,
            h: 800,
            refId: "comp_0",
            ind: 1,
            parent: 6
          },
          {
            ty: 3,
            nm: "",
            mn: "",
            sr: 0.5,
            st: 0,
            op: 131,
            ip: 0,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            hasMask: false,
            ao: 0,
            ks: {
              a: { a: 0, k: [400, 400, 0], ix: 1 },
              s: { a: 0, k: [30, 30, 100], ix: 6 },
              sk: { a: 0, k: 0 },
              p: { a: 0, k: [75.078, -24.852, 0], ix: 2 },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: 0, ix: 10 }
            },
            ef: [],
            ind: 2,
            parent: 6
          },
          {
            ty: 0,
            nm: "Hovering Dots",
            mn: "",
            sr: 0.5,
            st: 0,
            op: 220,
            ip: 130,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            hasMask: false,
            ao: 0,
            ks: {
              a: { a: 0, k: [400, 400, 0], ix: 1 },
              s: { a: 0, k: [30, 30, 100], ix: 6 },
              sk: { a: 0, k: 0 },
              p: { a: 0, k: [75.078, -24.852, 0], ix: 2 },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: 0, ix: 10 }
            },
            ef: [],
            w: 800,
            h: 800,
            refId: "comp_0",
            ind: 3,
            parent: 9
          },
          {
            ty: 4,
            nm: "blue 2",
            mn: "",
            sr: 1,
            st: 0,
            op: 220,
            ip: 130,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            hasMask: false,
            ao: 0,
            ks: {
              a: { a: 0, k: [199.902, 112.295, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.37, y: 1 },
                    s: [100, 100, 100],
                    t: 1
                  },
                  {
                    o: { x: 0.627, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [80, 80, 100],
                    t: 39
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [100, 100, 100],
                    t: 80
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [100, 100, 100],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [80, 80, 100],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [100, 100, 100],
                    t: 270
                  }
                ],
                ix: 6
              },
              sk: { a: 0, k: 0 },
              p: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0.333 },
                    i: { x: 0.667, y: 0.667 },
                    s: [454.866, 414.577, 0],
                    t: 130
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [454.866, 414.577, 0],
                    t: 180
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [464.866, 352.577, 0],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [454.866, 414.577, 0],
                    t: 270
                  }
                ],
                ix: 2
              },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.326, y: 1 },
                    s: [0],
                    t: 80
                  },
                  {
                    o: { x: 0.645, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [15],
                    t: 130
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [0],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [12],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [0],
                    t: 270
                  }
                ],
                ix: 10
              }
            },
            ef: [],
            shapes: [
              {
                ty: "gr",
                bm: 0,
                cl: "",
                ln: "",
                hd: false,
                mn: "ADBE Vector Group",
                nm: "Group 1",
                ix: 1,
                cix: 2,
                np: 2,
                it: [
                  {
                    ty: "sh",
                    bm: 0,
                    cl: "",
                    ln: "",
                    hd: false,
                    mn: "ADBE Vector Shape - Group",
                    nm: "Path 1",
                    ix: 1,
                    d: 1,
                    ks: {
                      a: 0,
                      k: {
                        c: true,
                        i: [
                          [0, -68.932],
                          [3.776, -11.889],
                          [2.924, -5.809],
                          [10.785, -10.088],
                          [0, 0],
                          [0, 0],
                          [11.327, 0],
                          [0, 68.932],
                          [-42.657, 19.847],
                          [-1.666, 0.677],
                          [-16.866, 0]
                        ],
                        o: [
                          [0, 13.148],
                          [-1.975, 6.273],
                          [-6.661, 13.321],
                          [0, 0],
                          [0, 0],
                          [-10.417, 2.827],
                          [-68.932, 0],
                          [0, -50.15],
                          [1.626, -0.755],
                          [14.676, -6.08],
                          [68.951, 0]
                        ],
                        v: [
                          [199.902, -37.167],
                          [194.093, 0.533],
                          [186.715, 18.656],
                          [160.266, 54.032],
                          [166.946, 112.295],
                          [107.773, 83.309],
                          [75.069, 87.666],
                          [-49.745, -37.167],
                          [22.479, -150.402],
                          [27.436, -152.57],
                          [75.069, -162]
                        ]
                      },
                      ix: 2
                    }
                  },
                  {
                    ty: "fl",
                    bm: 0,
                    cl: "",
                    ln: "",
                    hd: false,
                    mn: "ADBE Vector Graphic - Fill",
                    nm: "Fill 1",
                    c: { a: 0, k: [1, 1, 1], ix: 4 },
                    r: 1,
                    o: { a: 0, k: 100, ix: 5 }
                  },
                  {
                    ty: "tr",
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    sk: { a: 0, k: 0, ix: 4 },
                    p: { a: 0, k: [0, 0], ix: 2 },
                    r: { a: 0, k: 0, ix: 6 },
                    sa: { a: 0, k: 0, ix: 5 },
                    o: { a: 0, k: 100, ix: 7 }
                  }
                ]
              }
            ],
            ind: 4
          },
          {
            ty: 3,
            mn: "",
            sr: 1,
            st: 0,
            op: 374,
            ip: 219,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            tt: 0,
            hasMask: false,
            td: 0,
            ao: 0,
            ks: {
              a: { a: 0, k: [199.902, 112.295, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.37, y: 1 },
                    s: [-100, 100, 100],
                    t: 1
                  },
                  {
                    o: { x: 0.627, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [-80, 80, 100],
                    t: 39
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [-100, 100, 100],
                    t: 80
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [-100, 100, 100],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [-80, 80, 100],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [-100, 100, 100],
                    t: 270
                  }
                ],
                ix: 6
              },
              sk: { a: 0, k: 0 },
              p: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [51.866, 357.577, 0],
                    t: 180
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [41.866, 419.577, 0],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [51.866, 357.577, 0],
                    t: 270
                  }
                ],
                ix: 2
              },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.326, y: 1 },
                    s: [0],
                    t: 80
                  },
                  {
                    o: { x: 0.645, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [-17],
                    t: 130
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [0],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [12],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [0],
                    t: 270
                  }
                ],
                ix: 10
              }
            },
            ind: 5
          },
          {
            ty: 3,
            mn: "",
            sr: 1,
            st: 0,
            op: 131,
            ip: 0,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            tt: 0,
            hasMask: false,
            td: 0,
            ao: 0,
            ks: {
              a: { a: 0, k: [199.902, 112.295, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.37, y: 1 },
                    s: [-100, 100, 100],
                    t: 1
                  },
                  {
                    o: { x: 0.627, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [-80, 80, 100],
                    t: 39
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [-100, 100, 100],
                    t: 80
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [-100, 100, 100],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [-80, 80, 100],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [-100, 100, 100],
                    t: 270
                  }
                ],
                ix: 6
              },
              sk: { a: 0, k: 0 },
              p: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [51.866, 357.577, 0],
                    t: 180
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [41.866, 419.577, 0],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [51.866, 357.577, 0],
                    t: 270
                  }
                ],
                ix: 2
              },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.326, y: 1 },
                    s: [0],
                    t: 80
                  },
                  {
                    o: { x: 0.645, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [-17],
                    t: 130
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [0],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [12],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [0],
                    t: 270
                  }
                ],
                ix: 10
              }
            },
            ind: 6
          },
          {
            ty: 0,
            nm: "Hovering Dots",
            mn: "",
            sr: 0.5,
            st: 0,
            op: 344,
            ip: 0,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            hasMask: false,
            ao: 0,
            ks: {
              a: { a: 0, k: [400, 400, 0], ix: 1 },
              s: { a: 0, k: [30, 30, 100], ix: 6 },
              sk: { a: 0, k: 0 },
              p: { a: 0, k: [75.078, -24.852, 0], ix: 2 },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: 0, ix: 10 }
            },
            ef: [],
            w: 800,
            h: 800,
            refId: "comp_0",
            ind: 7,
            parent: 9
          },
          {
            ty: 4,
            nm: "blue 3",
            mn: "",
            sr: 1,
            st: 0,
            op: 397,
            ip: 219,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            hasMask: false,
            ao: 0,
            ks: {
              a: { a: 0, k: [199.902, 112.295, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.37, y: 1 },
                    s: [100, 100, 100],
                    t: 1
                  },
                  {
                    o: { x: 0.627, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [80, 80, 100],
                    t: 39
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [100, 100, 100],
                    t: 80
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [100, 100, 100],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [80, 80, 100],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [100, 100, 100],
                    t: 270
                  }
                ],
                ix: 6
              },
              sk: { a: 0, k: 0 },
              p: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0.333 },
                    i: { x: 0.667, y: 0.667 },
                    s: [454.866, 414.577, 0],
                    t: 130
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [454.866, 414.577, 0],
                    t: 180
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [464.866, 352.577, 0],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [454.866, 414.577, 0],
                    t: 270
                  }
                ],
                ix: 2
              },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.326, y: 1 },
                    s: [0],
                    t: 80
                  },
                  {
                    o: { x: 0.645, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [15],
                    t: 130
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [0],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [12],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [0],
                    t: 270
                  }
                ],
                ix: 10
              }
            },
            ef: [],
            shapes: [
              {
                ty: "gr",
                bm: 0,
                cl: "",
                ln: "",
                hd: false,
                mn: "ADBE Vector Group",
                nm: "Group 1",
                ix: 1,
                cix: 2,
                np: 2,
                it: [
                  {
                    ty: "sh",
                    bm: 0,
                    cl: "",
                    ln: "",
                    hd: false,
                    mn: "ADBE Vector Shape - Group",
                    nm: "Path 1",
                    ix: 1,
                    d: 1,
                    ks: {
                      a: 0,
                      k: {
                        c: true,
                        i: [
                          [0, -68.932],
                          [3.776, -11.889],
                          [2.924, -5.809],
                          [10.785, -10.088],
                          [0, 0],
                          [0, 0],
                          [11.327, 0],
                          [0, 68.932],
                          [-42.657, 19.847],
                          [-1.666, 0.677],
                          [-16.866, 0]
                        ],
                        o: [
                          [0, 13.148],
                          [-1.975, 6.273],
                          [-6.661, 13.321],
                          [0, 0],
                          [0, 0],
                          [-10.417, 2.827],
                          [-68.932, 0],
                          [0, -50.15],
                          [1.626, -0.755],
                          [14.676, -6.08],
                          [68.951, 0]
                        ],
                        v: [
                          [199.902, -37.167],
                          [194.093, 0.533],
                          [186.715, 18.656],
                          [160.266, 54.032],
                          [166.946, 112.295],
                          [107.773, 83.309],
                          [75.069, 87.666],
                          [-49.745, -37.167],
                          [22.479, -150.402],
                          [27.436, -152.57],
                          [75.069, -162]
                        ]
                      },
                      ix: 2
                    }
                  },
                  {
                    ty: "fl",
                    bm: 0,
                    cl: "",
                    ln: "",
                    hd: false,
                    mn: "ADBE Vector Graphic - Fill",
                    nm: "Fill 1",
                    c: { a: 0, k: [1, 1, 1], ix: 4 },
                    r: 1,
                    o: { a: 0, k: 100, ix: 5 }
                  },
                  {
                    ty: "tr",
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    sk: { a: 0, k: 0, ix: 4 },
                    p: { a: 0, k: [0, 0], ix: 2 },
                    r: { a: 0, k: 0, ix: 6 },
                    sa: { a: 0, k: 0, ix: 5 },
                    o: { a: 0, k: 100, ix: 7 }
                  }
                ]
              }
            ],
            ind: 8
          },
          {
            ty: 4,
            nm: "blue",
            mn: "",
            sr: 1,
            st: 0,
            op: 131,
            ip: 0,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            hasMask: false,
            ao: 0,
            ks: {
              a: { a: 0, k: [199.902, 112.295, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.37, y: 1 },
                    s: [100, 100, 100],
                    t: 1
                  },
                  {
                    o: { x: 0.627, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [80, 80, 100],
                    t: 39
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [100, 100, 100],
                    t: 80
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [100, 100, 100],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [80, 80, 100],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [100, 100, 100],
                    t: 270
                  }
                ],
                ix: 6
              },
              sk: { a: 0, k: 0 },
              p: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0.333 },
                    i: { x: 0.667, y: 0.667 },
                    s: [454.866, 414.577, 0],
                    t: 130
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [454.866, 414.577, 0],
                    t: 180
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [464.866, 352.577, 0],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [454.866, 414.577, 0],
                    t: 270
                  }
                ],
                ix: 2
              },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.326, y: 1 },
                    s: [0],
                    t: 80
                  },
                  {
                    o: { x: 0.645, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [15],
                    t: 130
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [0],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [12],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [0],
                    t: 270
                  }
                ],
                ix: 10
              }
            },
            ef: [],
            shapes: [
              {
                ty: "gr",
                bm: 0,
                cl: "",
                ln: "",
                hd: false,
                mn: "ADBE Vector Group",
                nm: "Group 1",
                ix: 1,
                cix: 2,
                np: 2,
                it: [
                  {
                    ty: "sh",
                    bm: 0,
                    cl: "",
                    ln: "",
                    hd: false,
                    mn: "ADBE Vector Shape - Group",
                    nm: "Path 1",
                    ix: 1,
                    d: 1,
                    ks: {
                      a: 0,
                      k: {
                        c: true,
                        i: [
                          [0, -68.932],
                          [3.776, -11.889],
                          [2.924, -5.809],
                          [10.785, -10.088],
                          [0, 0],
                          [0, 0],
                          [11.327, 0],
                          [0, 68.932],
                          [-42.657, 19.847],
                          [-1.666, 0.677],
                          [-16.866, 0]
                        ],
                        o: [
                          [0, 13.148],
                          [-1.975, 6.273],
                          [-6.661, 13.321],
                          [0, 0],
                          [0, 0],
                          [-10.417, 2.827],
                          [-68.932, 0],
                          [0, -50.15],
                          [1.626, -0.755],
                          [14.676, -6.08],
                          [68.951, 0]
                        ],
                        v: [
                          [199.902, -37.167],
                          [194.093, 0.533],
                          [186.715, 18.656],
                          [160.266, 54.032],
                          [166.946, 112.295],
                          [107.773, 83.309],
                          [75.069, 87.666],
                          [-49.745, -37.167],
                          [22.479, -150.402],
                          [27.436, -152.57],
                          [75.069, -162]
                        ]
                      },
                      ix: 2
                    }
                  },
                  {
                    ty: "fl",
                    bm: 0,
                    cl: "",
                    ln: "",
                    hd: false,
                    mn: "ADBE Vector Graphic - Fill",
                    nm: "Fill 1",
                    c: { a: 0, k: [1, 1, 1], ix: 4 },
                    r: 1,
                    o: { a: 0, k: 100, ix: 5 }
                  },
                  {
                    ty: "tr",
                    a: { a: 0, k: [0, 0], ix: 1 },
                    s: { a: 0, k: [100, 100], ix: 3 },
                    sk: { a: 0, k: 0, ix: 4 },
                    p: { a: 0, k: [0, 0], ix: 2 },
                    r: { a: 0, k: 0, ix: 6 },
                    sa: { a: 0, k: 0, ix: 5 },
                    o: { a: 0, k: 100, ix: 7 }
                  }
                ]
              }
            ],
            ind: 9
          },
          {
            ty: 0,
            nm: "Hovering Dots",
            mn: "",
            sr: 0.5,
            st: 0,
            op: 220,
            ip: 130,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            hasMask: false,
            ao: 0,
            ks: {
              a: { a: 0, k: [400, 400, 0], ix: 1 },
              s: { a: 0, k: [30, 30, 100], ix: 6 },
              sk: { a: 0, k: 0 },
              p: { a: 0, k: [75.078, -24.852, 0], ix: 2 },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: { a: 0, k: 0, ix: 10 }
            },
            ef: [],
            w: 800,
            h: 800,
            refId: "comp_0",
            ind: 10,
            parent: 6
          },
          {
            ty: 3,
            mn: "",
            sr: 1,
            st: 0,
            op: 220,
            ip: 130,
            hd: false,
            cl: "",
            ln: "",
            ddd: 0,
            bm: 0,
            tt: 0,
            hasMask: false,
            td: 0,
            ao: 0,
            ks: {
              a: { a: 0, k: [199.902, 112.295, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.37, y: 1 },
                    s: [-100, 100, 100],
                    t: 1
                  },
                  {
                    o: { x: 0.627, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [-80, 80, 100],
                    t: 39
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [-100, 100, 100],
                    t: 80
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [-100, 100, 100],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [-80, 80, 100],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [-100, 100, 100],
                    t: 270
                  }
                ],
                ix: 6
              },
              sk: { a: 0, k: 0 },
              p: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [51.866, 357.577, 0],
                    t: 180
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [41.866, 419.577, 0],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [51.866, 357.577, 0],
                    t: 270
                  }
                ],
                ix: 2
              },
              sa: { a: 0, k: 0 },
              o: { a: 0, k: 100, ix: 11 },
              r: {
                a: 1,
                k: [
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.326, y: 1 },
                    s: [0],
                    t: 80
                  },
                  {
                    o: { x: 0.645, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [-17],
                    t: 130
                  },
                  {
                    o: { x: 0.333, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [0],
                    t: 180
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.667, y: 1 },
                    s: [12],
                    t: 220
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [0],
                    t: 270
                  }
                ],
                ix: 10
              }
            },
            ind: 11
          }
        ],
        ddd: 0,
        h: 500,
        w: 500,
        meta: {
          a: "",
          k: "",
          d: "",
          g: "@lottiefiles/toolkit-js 0.21.3",
          tc: "#000000"
        },
        v: "5.7.0",
        fr: 60,
        op: 334,
        ip: 0,
        assets: [
          {
            nm: "",
            mn: "",
            layers: [
              {
                ty: 3,
                nm: "",
                mn: "",
                sr: 1,
                st: -60,
                op: 1828,
                ip: 0,
                hd: false,
                cl: "",
                ln: "",
                ddd: 0,
                bm: 0,
                hasMask: false,
                ao: 0,
                ks: {
                  a: { a: 0, k: [0, 0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100, 100], ix: 6 },
                  sk: { a: 0, k: 0 },
                  p: {
                    s: true,
                    x: { a: 0, k: 580, ix: 3 },
                    y: {
                      a: 1,
                      k: [
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: -60
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 0
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 60
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 120
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 180
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 240
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 300
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 360
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.833, y: 1 },
                          s: [380],
                          t: 420
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 480
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 540
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 600
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 660
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 720
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 780
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 840
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 900
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 960
                        },
                        {
                          o: { x: 0.167, y: 0.167 },
                          i: { x: 0.833, y: 0.833 },
                          s: [420],
                          t: 1020
                        }
                      ],
                      ix: 4
                    }
                  },
                  sa: { a: 0, k: 0 },
                  o: { a: 0, k: 100, ix: 11 },
                  r: { a: 0, k: 0, ix: 10 }
                },
                ef: [],
                ind: 1
              },
              {
                ty: 3,
                nm: "",
                mn: "",
                sr: 1,
                st: -40,
                op: 1828,
                ip: 0,
                hd: false,
                cl: "",
                ln: "",
                ddd: 0,
                bm: 0,
                hasMask: false,
                ao: 0,
                ks: {
                  a: { a: 0, k: [0, 0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100, 100], ix: 6 },
                  sk: { a: 0, k: 0 },
                  p: {
                    s: true,
                    x: { a: 0, k: 460, ix: 3 },
                    y: {
                      a: 1,
                      k: [
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: -40
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 20
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 80
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 140
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 200
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 260
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 320
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 380
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.833, y: 1 },
                          s: [380],
                          t: 440
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 500
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 560
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 620
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 680
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 740
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 800
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 860
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 920
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 980
                        },
                        {
                          o: { x: 0.167, y: 0.167 },
                          i: { x: 0.833, y: 0.833 },
                          s: [420],
                          t: 1040
                        }
                      ],
                      ix: 4
                    }
                  },
                  sa: { a: 0, k: 0 },
                  o: { a: 0, k: 100, ix: 11 },
                  r: { a: 0, k: 0, ix: 10 }
                },
                ef: [],
                ind: 2
              },
              {
                ty: 3,
                nm: "",
                mn: "",
                sr: 1,
                st: -20,
                op: 1828,
                ip: 0,
                hd: false,
                cl: "",
                ln: "",
                ddd: 0,
                bm: 0,
                hasMask: false,
                ao: 0,
                ks: {
                  a: { a: 0, k: [0, 0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100, 100], ix: 6 },
                  sk: { a: 0, k: 0 },
                  p: {
                    s: true,
                    x: { a: 0, k: 340, ix: 3 },
                    y: {
                      a: 1,
                      k: [
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: -20
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 40
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 100
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 160
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 220
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 280
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 340
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 400
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.833, y: 1 },
                          s: [380],
                          t: 460
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 520
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 580
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 640
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 700
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 760
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 820
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 880
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 940
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 1000
                        },
                        {
                          o: { x: 0.167, y: 0.167 },
                          i: { x: 0.833, y: 0.833 },
                          s: [420],
                          t: 1060
                        }
                      ],
                      ix: 4
                    }
                  },
                  sa: { a: 0, k: 0 },
                  o: { a: 0, k: 100, ix: 11 },
                  r: { a: 0, k: 0, ix: 10 }
                },
                ef: [],
                ind: 3
              },
              {
                ty: 3,
                nm: "",
                mn: "",
                sr: 1,
                st: 0,
                op: 1828,
                ip: 0,
                hd: false,
                cl: "",
                ln: "",
                ddd: 0,
                bm: 0,
                hasMask: false,
                ao: 0,
                ks: {
                  a: { a: 0, k: [0, 0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100, 100], ix: 6 },
                  sk: { a: 0, k: 0 },
                  p: {
                    s: true,
                    x: { a: 0, k: 220, ix: 3 },
                    y: {
                      a: 1,
                      k: [
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 0
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 60
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 120
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 180
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 240
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 300
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 360
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 420
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 480
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 540
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 600
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 660
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 720
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 780
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 840
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 900
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [420],
                          t: 960
                        },
                        {
                          o: { x: 0.333, y: 0 },
                          i: { x: 0.667, y: 1 },
                          s: [380],
                          t: 1020
                        },
                        {
                          o: { x: 0.167, y: 0.167 },
                          i: { x: 0.833, y: 0.833 },
                          s: [420],
                          t: 1080
                        }
                      ],
                      ix: 4
                    }
                  },
                  sa: { a: 0, k: 0 },
                  o: { a: 0, k: 100, ix: 11 },
                  r: { a: 0, k: 0, ix: 10 }
                },
                ef: [],
                ind: 4
              }
            ],
            id: "comp_0",
            fr: 30
          }
        ]
      }}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof LottieWrapper;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicChat1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicChat1__VariantsArgs;
    args?: PlasmicChat1__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicChat1__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicChat1__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicChat1__ArgProps,
          internalVariantPropNames: PlasmicChat1__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicChat1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicChat1";
  } else {
    func.displayName = `PlasmicChat1.${nodeName}`;
  }
  return func;
}

export const PlasmicChat1 = Object.assign(
  // Top-level PlasmicChat1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicChat1
    internalVariantProps: PlasmicChat1__VariantProps,
    internalArgProps: PlasmicChat1__ArgProps
  }
);

export default PlasmicChat1;
/* prettier-ignore-end */
